version: 2
updates:
  - package-ecosystem: github-actions
    schedule:
      interval: weekly
    directory: /
    commit-message:
      prefix: ":arrow_up: "

  - package-ecosystem: uv
    schedule:
      interval: weekly
    directory: /
    commit-message:
      prefix: ":arrow_up: "
