on:
  workflow_dispatch:
  schedule:
    - cron: 0 15 * * * # everyday 00:00 JST (Midnight)

jobs:
  update-flake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@1ca7d21a94afc7c957383a2d217460d980de4934 # v31.10.1

      - name: update-flake
        run: nix flake update

      - name: git-commit
        env:
          GIT_AUTHOR_NAME: "Peacock"
          GIT_AUTHOR_EMAIL: "33555487+peacock0803sz@users.noreply.github.com"
          GIT_COMMITTER_NAME: "github-actions[bot]"
          GIT_COMMITTER_EMAIL: "github-actions[bot]@users.noreply.github.com"
        run: |
          if (( $(git status --short --untracked-files | wc -l) < 1 )); then exit 0; fi
          git add flake.lock
          git commit -m ":snowflake: Update flake.lock"
          git push origin HEAD
